source 'http://rubygems.org'

gem 'sinatra'
gem 'imdb', '~> 0.8.2'
gem 'activerecord', '~> 4.2.5.1'
gem 'sqlite3', '~> 1.3.11'
gem 'httparty', '~> 0.6.1'
gem 'tvdb_party', '~> 0.8.1'
gem 'rspec', '~> 3.4'
gem 'rake'
